### ISSUE TITLE
Xcode 7.0

### ISSUE THREAD

**Issue by allyrgb** [nghialv/Sapporo#6]
Will you be updating this to Xcode 7.0, please?  It currently will not build for me.  Thanks.
Edit: I'm getting init() is unavailable for UICollectionViewTransitionLayout().

**Comment by Ged2323** [comment]
same problem here too.

**Comment by roro95** [comment]
same problem too

**Comment by nghialv** [comment]
Thanks for reporting. I will check it.

**Comment by flyingmate** [comment]
Build error in xcode 7.3. I like the concept not using delegate and datasource, hope to use this with Hakuba(it's working fine with xcode 7.3 and swift 2.2)

**Comment by nghialv** [comment]
Thanks for your using. I will fix this problem this weekend.

**Comment by nghialv** [comment]
I have just release a new version. Please use it.
